//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Itog8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Длительность.
    /// </summary>
    // *** Start programmer edit section *** (Длительность CustomAttributes)

    // *** End programmer edit section *** (Длительность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДлительностьE", new string[] {
            "Номер as \'Длительность\'"})]
    [View("ДлительностьL", new string[] {
            "Номер as \'Длительность\'"})]
    public class Длительность : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомер;
        
        // *** Start programmer edit section *** (Длительность CustomMembers)

        // *** End programmer edit section *** (Длительность CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Длительность.Номер CustomAttributes)

        // *** End programmer edit section *** (Длительность.Номер CustomAttributes)
        [StrLen(255)]
        public virtual string Номер
        {
            get
            {
                // *** Start programmer edit section *** (Длительность.Номер Get start)

                // *** End programmer edit section *** (Длительность.Номер Get start)
                string result = this.fНомер;
                // *** Start programmer edit section *** (Длительность.Номер Get end)

                // *** End programmer edit section *** (Длительность.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Длительность.Номер Set start)

                // *** End programmer edit section *** (Длительность.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Длительность.Номер Set end)

                // *** End programmer edit section *** (Длительность.Номер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДлительностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДлительностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДлительностьE", typeof(IIS.Itog8.Длительность));
                }
            }
            
            /// <summary>
            /// "ДлительностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДлительностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДлительностьL", typeof(IIS.Itog8.Длительность));
                }
            }
        }
    }
}
