//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Itog8
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Затр время.
    /// </summary>
    // *** Start programmer edit section *** (ЗатрВремя CustomAttributes)

    // *** End programmer edit section *** (ЗатрВремя CustomAttributes)
    [AutoAltered()]
    [Caption("Затр время")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗатрВремяE", new string[] {
            "Наименование as \'Время\'"})]
    [View("ЗатрВремяL", new string[] {
            "Наименование as \'Время\'"})]
    public class ЗатрВремя : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (ЗатрВремя CustomMembers)

        // *** End programmer edit section *** (ЗатрВремя CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ЗатрВремя.Наименование CustomAttributes)

        // *** End programmer edit section *** (ЗатрВремя.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ЗатрВремя.Наименование Get start)

                // *** End programmer edit section *** (ЗатрВремя.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ЗатрВремя.Наименование Get end)

                // *** End programmer edit section *** (ЗатрВремя.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗатрВремя.Наименование Set start)

                // *** End programmer edit section *** (ЗатрВремя.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ЗатрВремя.Наименование Set end)

                // *** End programmer edit section *** (ЗатрВремя.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗатрВремяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗатрВремяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗатрВремяE", typeof(IIS.Itog8.ЗатрВремя));
                }
            }
            
            /// <summary>
            /// "ЗатрВремяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗатрВремяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗатрВремяL", typeof(IIS.Itog8.ЗатрВремя));
                }
            }
        }
    }
}
